# When this action will be executed
on:
  # Automatically trigger it when changes are pushed to specific branches or paths
  push:
    branches:
      - main
      - master
    paths:
      - 'backend/**'
      
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: tolex.azurecr.io
          username: ${{ secrets.MY_USERNAME }}
          password: ${{ secrets.MY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tolex.azurecr.io/crowdbotics:${{ github.sha }}
          file: ./backend/Dockerfile
          context: ./backend/
          build-args: |
            SECRET_KEY=bonjour
            PORT=8000
            
  deploy:
    runs-on: ubuntu-latest
    needs: build
   
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CROWDBOTICS_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n crowdbotics -g t-rg-crowdbotics --server crowdbotics.azurecr.io --username ${{ secrets.CROWDBOTICS_REGISTRY_USERNAME }} --password ${{ secrets.CROWDBOTICS_REGISTRY_PASSWORD }}
            az containerapp update -n crowdbotics -g t-rg-crowdbotics --image crowdbotics.azurecr.io/crowdbotics:${{ github.sha }}
